# Site settings
title: Digital Alchemy
email: your-email@domain.com
description: "This is a blog chronicling the progress of team Digital Alchemy as they battle though a intense 7 week code learning programme"
baseurl: "/Digital-alchemy2.0"
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
